### ISSUE TITLE
Cannot add additional parameters to cluster "Default" on first run of role oVirt.infra after engine was installed

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible-infra#9] opened 2017-12-14 11:07 UTC
It is impossible update cluster "Default" on first run of role oVirt.infra

vars:
mac_pools:
  - mac_pool_name: "specific_mac220"
    mac_pool_ranges:
     - "AA:BB:CC:DD:EE:FF,AA:BB:CC:DD:EF:FF"
 
clusters:
  - name: "Default"
    mac_pool: specific_mac220

TASK [oVirt.infra/roles/oVirt.clusters : Add clusters] *************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'architecture'
[DEPRECATION WARNING]: The 'ovirt_clusters' module is being renamed 
'ovirt_cluster'. This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [localhost] (item={u'name': u'Default', u'mac_pool': u'specific_mac220'}) => {"changed": false, "failed": true, "item": {"mac_pool": "specific_mac220", "name": "Default"}, "msg": "'NoneType' object has no attribute 'architecture'"}

**Comment by mwperina** [comment] 2017-12-14 11:12
Hmm, I think that's one of the known issues, because architecture type for Default cluster is set once you add first host into it. Although otherwise there's no way how to create a new cluster without architecture type being set. So not sure if we can do anything about it

**Comment by machacekondra** [comment] 2017-12-14 11:25
I think the issue is here:

 https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_cluster.py#L536

REST API don't return cpu/arch elelemnt in case it's not set, so we fail the update check. We can just ignore that comparsion in case it's not set, so it's resolve the issue.

**Comment by mwperina** [comment] 2017-12-14 12:22
> I think the issue is here:
> 
> https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_cluster.py#L536
> 
> REST API don't return cpu/arch elelemnt in case it's not set, so we fail the update check. We can just ignore that comparsion in case it's not set, so it's resolve the issue.

+1

**Comment by machacekondra** [comment] 2018-01-04 11:41
Fixed by: https://github.com/ansible/ansible/pull/34446

**Closed as completed** 2018-01-04 11:41 UTC
Labels: fixed_in_ansible_2.5
